Standardized API's
credebl/studio pull request #265
Opened 2023-09-14 06:55 UTC by bhavanakarwade

## What ## 

- Refactored the API endpoints in the User, Organization, Auth and Agent models.
- Improved code Organization and readability.
- Updated API documentation.

## Why ##

- To provide better support for future feature development.
- To make the API more user-friendly and intuitive for developers.

## How ##

- Reviewed the existing Codebase in the User, Organization, Auth and Agent models.
- Refactored the API endpoints using best practices and design patterns.
- Updated API documentation to reflect the changes made.
- Ran tests to ensure that the refactored code functions correctly.

2023-09-14 09:40 UTC, nishad-ayanworks commented on src/api/Auth.ts
> +    password:string | undefined
What is the use to set `undefined`

2023-09-14 09:43 UTC, nishad-ayanworks commented on src/api/Fido.ts
> +export const verifyRegistration = async (payload:any, userEmail:string) => {
Try not to use `any` data type.

2023-09-14 09:44 UTC, nishad-ayanworks commented on src/components/Profile/EditUserProfile.tsx
> +      // id: userProfileInfo?.id,
please remove commented code

2023-09-14 09:47 UTC, nishad-ayanworks requested changes
Please resolve the comments

2023-09-14 10:24 UTC, bhavanakarwade commented on src/components/Profile/EditUserProfile.tsx
> +      // id: userProfileInfo?.id,
Resolved

2023-09-14 10:25 UTC, bhavanakarwade commented on src/api/Auth.ts
> +    password:string | undefined
Resolved

2023-09-14 10:26 UTC, bhavanakarwade commented
> Please resolve the comments

Resolved

2023-09-20 10:42 UTC, nishad-ayanworks approved these changes
LG

2023-09-20 10:55 UTC, merged