feat: Implement w3c issuance with connection,email and bulk.
credebl/studio pull request #721
Opened 2024-07-23 18:00 UTC by pranalidhanavade

### What 

Implemented W3C issuance with connections.
- Implemented changes in astro routes for W3C issuance.
- Refactored existing flow of issuance with connections. 
- Implemented Payload changes for W3C issuance with connections.

Implemented W3C email-issuance.
 - Implemented changes in astro routes for W3C issuance.
 - Refactored existing flow of issuance with email.
 - Implemented Payload changes for W3C issuance with email.
 - Implement W3C bulk-issuance.

Implement W3C bulk-issuance.
 - Refactored existing flow of bulk-issuance.
 - Implemented payload changes in API for download and upload csv file for bulk issuance.

2024-07-30 11:10 UTC, bhavanakarwade requested changes

2024-07-30 11:10 UTC, bhavanakarwade commented on src/components/Issuance/EmailIssuance.tsx
> +		credentialDefinitionId:credDef.credentialDefinitionId,
We can use object destructuring here to fetch the attributes of the credDef object

2024-07-30 11:10 UTC, bhavanakarwade commented on src/components/Issuance/EmailIssuance.tsx
> +        existingData?.formData.forEach((entry: { email: any; attributes: any[] }) => {
Use correct dataType instead of using any dataType

2024-07-30 11:10 UTC, bhavanakarwade commented on src/components/Issuance/EmailIssuance.tsx
> +						"https://www.w3.org/2018/credentials/v1",
We can move these hardcoded values to one common file and use those variables when forming the payload

2024-07-30 11:10 UTC, bhavanakarwade commented on src/components/Issuance/interface.ts
> +export interface W3cSchemaDetails {
We are following `I` prefix while creating an interface

2024-07-30 11:10 UTC, bhavanakarwade commented on src/components/Issuance/interface.ts
> +        credentialSubject: {
Create an separate interface for it and then use it

2024-07-30 11:10 UTC, bhavanakarwade commented on src/components/Issuance/Issuance.tsx
> +								"https://www.w3.org/2018/credentials/v1",
We can move these hardcoded values to one common file and use those variables when forming the payload

2024-07-30 14:53 UTC, tipusinghaw approved these changes

2024-07-31 07:46 UTC, bhavanakarwade approved these changes

2024-07-31 07:46 UTC, merged